module.exports = [
  {
    id: 1,
    nombre: "Limonero",
    precio: 45.0,
    descripcion:
      "Árbol de limón de aproximadamente 1.5 metros. Ideal para cultivar en macetas o directamente en el suelo. Necesita mucho sol.",
    imagen: [
      "../../../public/images/productos/limonero-limones.jpg",
      "../../../public/images/productos/limonero2.jpg",
      "../../../public/images/productos/limonero3.jpg",
    ],
    categoria: ["árboles frutales", "plantas de exterior"],
    stock: 20,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 2,
    nombre: "Naranjo",
    precio: 50.0,
    descripcion:
      "Árbol de naranja de aproximadamente 2 metros. Produce naranjas dulces y es ideal para cultivar en climas cálidos.",
    imagen: [
      "../../../public/images/productos/naranjo.jpg",
      "../../../public/images/productos/naranjo2.jpg",
      "../../../public/images/productos/naranjo3.jpg",
    ],
    categoria: ["árboles frutales", "plantas de exterior"],
    stock: 15,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 3,
    nombre: "Manzano",
    precio: 55.0,
    descripcion:
      "Árbol de manzana de aproximadamente 1.5 metros. Requiere un clima fresco y un suelo bien drenado.",
    imagen: [
      "../../../public/images/productos/manzano.jpg",
      "../../../public/images/productos/manzano2.jpg",
      "../../../public/images/productos/manzano3.jpg",
    ],
    categoria: ["árboles frutales", "plantas de exterior"],
    stock: 10,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 4,
    nombre: "Vid",
    precio: 40.0,
    descripcion:
      "Planta de uva que puede crecer en forma de enredadera. Requiere mucha luz y riego moderado.",
    imagen: [
      "../../../public/images/productos/uva.jpg",
      "../../../public/images/productos/uva2.jpg",
      "../../../public/images/productos/uva3.jpg",
    ],
    categoria: ["árboles frutales", "plantas de exterior"],
    stock: 12,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 5,
    nombre: "Peral",
    precio: 48.0,
    descripcion:
      "Árbol de peras de aproximadamente 1.8 metros. Ideal para cultivar en climas templados y suelos bien drenados.",
    imagen: [
      "../../../public/images/productos/peral.jpg",
      "../../../public/images/productos/peral2.jpg",
      "../../../public/images/productos/peral3.jpg",
    ],
    categoria: ["árboles frutales", "plantas de exterior"],
    stock: 8,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 6,
    nombre: "Ciruelo",
    precio: 42.0,
    descripcion:
      "Árbol de ciruelas de aproximadamente 2 metros. Produce ciruelas dulces y jugosas, ideal para climas templados y suelos bien drenados.",
    imagen: [
      "../../../public/images/productos/ciruelo.jpg",
      "../../../public/images/productos/ciruelo2.jpg",
      "../../../public/images/productos/ciruelo3.jpg",
    ],
    categoria: ["árboles frutales", "plantas de exterior"],
    stock: 10,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 7,
    nombre: "Alocasia",
    precio: 30.0,
    descripcion:
      "Planta tropical con grandes hojas verdes. Requiere luz indirecta y un ambiente húmedo para su óptimo desarrollo.",
    imagen: [
      "../../../public/images/productos/alocasia.jpg",
      "../../../public/images/productos/alocasia2.jpg",
      "../../../public/images/productos/alocasia3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 15,
    cantidad_agua: "alta",
    cantidad_sol: "moderada",
    dificultad_cuidado: "moderada",
  },
  {
    id: 8,
    nombre: "Crassula Tetragona",
    precio: 18.0,
    descripcion:
      "Suculenta de crecimiento vertical, fácil de cuidar. Ideal para principiantes y requiere luz brillante.",
    imagen: [
      "../../../public/images/productos/crassula-tetragona.png",
      "../../../public/images/productos/crassula-tetragona2.jpg",
      "../../../public/images/productos/crassula-tetragona3.jpg",
    ],
    categoria: ["cactus y suculentas"],
    stock: 35,
    cantidad_agua: "baja",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 9,
    nombre: "Lirio de la Paz",
    precio: 28.0,
    descripcion:
      "Conocido como Lirio de la Paz, es una planta de interior que purifica el aire. Ideal para ambientes con luz indirecta y riego moderado.",
    imagen: [
      "../../../public/images/productos/spathiphyllum-wallisii.png",
      "../../../public/images/productos/spathiphyllum-wallisii2.webp",
      "../../../public/images/productos/spathiphyllum-wallisii3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 25,
    cantidad_agua: "moderada",
    cantidad_sol: "baja",
    dificultad_cuidado: "baja",
  },
  {
    id: 10,
    nombre: "Zamioculca",
    precio: 32.0,
    descripcion:
      "Planta de interior muy resistente, con hojas gruesas y brillantes. Requiere poca luz y riego moderado, perfecta para principiantes.",
    imagen: [
      "../../../public/images/productos/zamioculca.jpg",
      "../../../public/images/productos/zamioculca2.webp",
      "../../../public/images/productos/zamioculca3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 40,
    cantidad_agua: "baja",
    cantidad_sol: "baja",
    dificultad_cuidado: "baja",
  },
  {
    id: 11,
    nombre: "Eucalipto Plateado",
    precio: 40.0,
    descripcion:
      "Eucalipto Plateado, ideal para jardines y arreglos florales. Necesita mucho sol y riego moderado. Sus hojas tienen un aroma distintivo.",
    imagen: [
      "../../../public/images/productos/eucalyptus-cinerea.jpg",
      "../../../public/images/productos/eucalyptus-cinerea2.jpg",
      "../../../public/images/productos/eucalyptus-cinerea3.jpg",
    ],
    categoria: ["plantas de exterior"],
    stock: 30,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 12,
    nombre: "Ave del Paraíso",
    precio: 50.0,
    descripcion:
      "Strelitzia Nicolai, planta tropical con hojas grandes y flores exóticas que parecen aves. Ideal para interiores luminosos y climas cálidos.",
    imagen: [
      "../../../public/images/productos/strelitzia.jpg",
      "../../../public/images/productos/strelitzia2.jpg",
      "../../../public/images/productos/strelitzia3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 10,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 13,
    nombre: "Ficus Bonsái",
    precio: 55.0,
    descripcion:
      "Ficus retusa, ideal para cultivadores de bonsáis. Requiere luz indirecta y un riego moderado. Perfecto para decoración interior.",
    imagen: [
      "../../../public/images/productos/ficus-retusa.jpg",
      "../../../public/images/productos/ficus-retusa2.jpg",
      "../../../public/images/productos/ficus-retusa3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 12,
    cantidad_agua: "moderada",
    cantidad_sol: "moderada",
    dificultad_cuidado: "moderada",
  },
  {
    id: 14,
    nombre: "Monstera Pandurata",
    precio: 48.0,
    descripcion:
      "Planta tropical con hojas grandes y decorativas. Prefiere luz brillante y un riego moderado. Ideal para interiores.",
    imagen: [
      "../../../public/images/productos/pandurata.jpg",
      "../../../public/images/productos/pandurata2.jpg",
      "../../../public/images/productos/pandurata3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 8,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 15,
    nombre: "Monstera",
    precio: 45.0,
    descripcion:
      "Planta popular con hojas grandes y recortadas, ideal para interiores. Prefiere luz indirecta y riego moderado.",
    imagen: [
      "../../../public/images/productos/monstera.jpg",
      "../../../public/images/productos/monstera2.jpg",
      "../../../public/images/productos/monstera3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 15,
    cantidad_agua: "moderada",
    cantidad_sol: "moderada",
    dificultad_cuidado: "moderada",
  },
  {
    id: 16,
    nombre: "Calathea",
    precio: 35.0,
    descripcion:
      "Planta de interior conocida por sus hojas decorativas y patrones únicos. Prefiere luz indirecta y un ambiente húmedo.",
    imagen: [
      "../../../public/images/productos/calathea.jpg",
      "../../../public/images/productos/calathea2.jpg",
      "../../../public/images/productos/calathea3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 15,
    cantidad_agua: "alta",
    cantidad_sol: "baja",
    dificultad_cuidado: "moderada",
  },
  {
    id: 17,
    nombre: "Gomero",
    precio: 60.0,
    descripcion:
      "Árbol del caucho, planta de interior que puede crecer considerablemente. Requiere luz indirecta brillante y riego moderado.",
    imagen: [
      "../../../public/images/productos/gomero.jpg",
      "../../../public/images/productos/gomero2.jpg",
      "../../../public/images/productos/gomero3jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 10,
    cantidad_agua: "moderada",
    cantidad_sol: "moderada",
    dificultad_cuidado: "baja",
  },
  {
    id: 18,
    nombre: "Cactus Genérico",
    precio: 15.0,
    descripcion:
      "Cactus fácil de cuidar, ideal para interiores o exteriores. Requiere luz brillante y riego escaso.",
    imagen: [
      "../../../public/images/productos/cactus.png",
      "../../../public/images/productos/cactus2.jpg",
      "../../../public/images/productos/cactus3.jpg",
    ],
    categoria: ["cactus y suculentas", "plantas de exterior"],
    stock: 50,
    cantidad_agua: "baja",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 19,
    nombre: "Hortensia",
    precio: 40.0,
    descripcion:
      "Planta ornamental con flores grandes y coloridas. Requiere luz indirecta y un suelo húmedo.",
    imagen: [
      "../../../public/images/productos/hortensia.jpg",
      "../../../public/images/productos/hortensia2.jpg",
      "../../../public/images/productos/hortensia3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 12,
    cantidad_agua: "alta",
    cantidad_sol: "moderada",
    dificultad_cuidado: "moderada",
  },
  {
    id: 20,
    nombre: "Jazmín",
    precio: 25.0,
    descripcion:
      "Planta trepadora con flores blancas y fragancia intensa. Ideal para exteriores y requiere sol directo.",
    imagen: [
      "../../../public/images/productos/jazmin.jpg",
      "../../../public/images/productos/jazmin2.jpg",
      "../../../public/images/productos/jazmin3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 15,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 21,
    nombre: "Rosas",
    precio: 30.0,
    descripcion:
      "Planta de rosas con flores variadas en color y fragancia. Ideal para jardines y requiere sol directo.",
    imagen: [
      "../../../public/images/productos/rosas.jpg",
      "../../../public/images/productos/rosas2.jpg",
      "../../../public/images/productos/rosas3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 20,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
  {
    id: 22,
    nombre: "Potus",
    precio: 25.0,
    descripcion:
      "Planta trepadora de interior muy resistente, con hojas verdes brillantes. Fácil de cuidar y purifica el aire.",
    imagen: [
      "../../../public/images/productos/potus.jpg",
      "../../../public/images/productos/potus2.jpg",
      "../../../public/images/productos/potus3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 25,
    cantidad_agua: "moderada",
    cantidad_sol: "baja",
    dificultad_cuidado: "baja",
  },
  {
    id: 23,
    nombre: "Orquídea",
    precio: 60.0,
    descripcion:
      "Planta exótica con flores llamativas, ideal para decoración de interiores. Requiere luz indirecta y un ambiente húmedo.",
    imagen: [
      "../../../public/images/productos/orquidea.jpg",
      "../../../public/images/productos/orquidea2.jpg",
      "../../../public/images/productos/orquidea3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de interior"],
    stock: 15,
    cantidad_agua: "alta",
    cantidad_sol: "moderada",
    dificultad_cuidado: "moderada",
  },
  {
    id: 24,
    nombre: "Lavanda",
    precio: 35.0,
    descripcion:
      "Planta aromática conocida por sus flores moradas y su fragancia calmante. Ideal para exteriores y jardines. Requiere sol pleno y riego moderado.",
    imagen: [
      "../../../public/images/productos/lavanda.jpg",
      "../../../public/images/productos/lavanda2.jpg",
      "../../../public/images/productos/lavanda3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 20,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 25,
    nombre: "Suculenta",
    precio: 15.0,
    descripcion:
      "Planta de bajo mantenimiento con hojas carnosas que almacenan agua. Ideal para interiores o exteriores con mucha luz natural.",
    imagen: [
      "../../../public/images/productos/suculenta.jpg",
      "../../../public/images/productos/suculenta2.jpg",
      "../../../public/images/productos/suculenta3.jpg",
    ],
    categoria: ["cactus y suculentas"],
    stock: 50,
    cantidad_agua: "baja",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 26,
    nombre: "Sansevieria",
    precio: 27.0,
    descripcion:
      "Planta de interior conocida como 'Lengua de suegra', muy resistente y de bajo mantenimiento. Purifica el aire y tolera condiciones de poca luz.",
    imagen: [
      "../../../public/images/productos/sansevieria-trifasciata.jpg",
      "../../../public/images/productos/sansevieria.2.webp",
      "../../../public/images/productos/sansevieria3.jpg",
    ],
    categoria: ["plantas de interior"],
    stock: 30,
    cantidad_agua: "baja",
    cantidad_sol: "baja",
    dificultad_cuidado: "baja",
  },
  {
    id: 27,
    nombre: "Enredadera Japonesa",
    precio: 38.0,
    descripcion:
      "También conocida como Enredadera Japonesa, es una planta trepadora de rápido crecimiento, ideal para cubrir muros o pérgolas. Prefiere exteriores con sol o semisombra.",
    imagen: [
      "../../../public/images/productos/parthenocissus-tricuspidata.jpg",
      "../../../public/images/productos/enredadera2.jpg",
      "../../../public/images/productos/enredadera3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 18,
    cantidad_agua: "moderada",
    cantidad_sol: "moderada",
    dificultad_cuidado: "baja",
  },
  {
    id: 28,
    nombre: "Buganvilla",
    precio: 35.0,
    descripcion:
      "Planta ornamental trepadora, conocida por sus vibrantes flores en tonos variados. Ideal para decorar patios y muros.",
    imagen: [
      "../../../public/images/productos/buganvilla.jpg",
      "../../../public/images/productos/buganvilla2.jpg",
      "../../../public/images/productos/buganvilla3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 12,
    cantidad_agua: "baja",
    cantidad_sol: "alta",
    dificultad_cuidado: "baja",
  },
  {
    id: 29,
    nombre: "Buxus",
    precio: 25.0,
    descripcion:
      "Arbusto perenne, ideal para setos y borduras. Su follaje denso proporciona un aspecto elegante a jardines.",
    imagen: [
      "../../../public/images/productos/buxus.jpg",
      "../../../public/images/productos/buxus2.jpg",
      "../../../public/images/productos/buxus3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 20,
    cantidad_agua: "baja",
    cantidad_sol: "moderada",
    dificultad_cuidado: "baja",
  },
  {
    id: 30,
    nombre: "Tulipán",
    precio: 25.0,
    descripcion:
      "Flor bulbosa muy apreciada por su elegancia y colores vibrantes. Ideal para jardines y macetas.",
    imagen: [
      "../../../public/images/productos/tulipan.jpg",
      "../../../public/images/productos/tulipan2.jpg",
      "../../../public/images/productos/tulipan3.jpg",
    ],
    categoria: ["plantas ornamentales", "plantas de exterior"],
    stock: 20,
    cantidad_agua: "moderada",
    cantidad_sol: "alta",
    dificultad_cuidado: "moderada",
  },
];
